# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 12:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Party',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('debit_amount', models.IntegerField(blank=True)),
                ('cradit_amount', models.IntegerField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('owener_name', models.CharField(max_length=30)),
                ('purchase_price', models.IntegerField(blank=True)),
                ('sell_price', models.IntegerField(blank=True)),
                ('received_date', models.DateField(blank=True)),
                ('return_date', models.DateField(blank=True)),
            ],
        ),
    ]
