# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 15:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100)),
                ('owener_name', models.CharField(max_length=30)),
                ('purchase_price', models.IntegerField(blank=True)),
                ('sell_price', models.IntegerField(blank=True)),
                ('received_date', models.DateField(blank=True)),
                ('description', models.CharField(max_length=300)),
            ],
        ),
        migrations.DeleteModel(
            name='Phone',
        ),
    ]
