# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20171111_2037'),
    ]

    operations = [
        migrations.RenameField(
            model_name='party',
            old_name='cradit_amount',
            new_name='credit_amount',
        ),
    ]
