# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20171111_2142'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='owener_name',
            new_name='owner_name',
        ),
    ]
