# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-11 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20171111_2143'),
    ]

    operations = [
        migrations.AlterField(
            model_name='party',
            name='credit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='party',
            name='debit_amount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
